"""
Probabilistic models for play outcome simulation.

Lazy imports are used to avoid circular dependencies during package initialization.
"""

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .model import (
        TypedModel,
        ModelExecutionError,
        InvalidModelReturnType,
        ModelContext,
    )
    from .offense import (
        PlayTypeModel,
        DefaultPlayTypeModel,
        OffensivePlayCallModel,
        DefaultOffensivePlayCallModel,
        RushYardsGainedModel,
        DefaultRushYardsGainedModel,
        AirYardsModel,
        DefaultAirYardsModel,
        CompletionModel,
        DefaultCompletionModel,
        YardsAfterCatchModel,
        DefaultYardsAfterCatchModel,
        PlayTypeContext,
        OffPlayCallContext,
        RushYardsGainedContext,
        AirYardsContext,
        CompletionContext,
        YardsAfterCatchContext,
    )
    from .defense import (
        DefensivePlayCallModel,
        DefaultDefensivePlayCallModel,
        DefPlayCallContext,
    )
    from .personnel import (
        OffensivePlayerAssignmentModel,
        DefaultOffensivePlayerAssignmentModel,
        DefensivePlayerAssignmentModel,
        DefaultDefensivePlayerAssignmentModel,
        PasserSelectionModel,
        DefaultPasserSelectionModel,
        TargettedSelectionModel,
        DefaultTargettedSelectionModel,
        RusherSelectionModel,
        DefaultRusherSelectionModel,
        KickerSelectionModel,
        DefaultKickerSelectionModel,
        PunterSelectionModel,
        DefaultPunterSelectionModel,
        PlaceKickerSelectionModel,
        DefaultPlaceKickerSelectionModel,
        PuntReturnerSelectionModel,
        DefaultPuntReturnerSelectionModel,
        KickoffReturnerSelectionModel,
        DefaultKickoffReturnerSelectionModel,
        PlayerAssignmentContext,
        PasserSelectionContext,
        TargettedSelectionContext,
        RusherSelectionContext,
        KickerSelectionContext,
        PunterSelectionContext,
        PlaceKickerSelectionContext,
        PuntReturnerSelectionContext,
        KickoffReturnerSelectionContext,
    )
    from .specialteams import (
        PuntDistanceModel,
        DefaultPuntDistanceModel,
        PuntReturnDistanceModel,
        DefaultPuntReturnDistanceModel,
        FieldGoalModel,
        DefaultFieldGoalModel,
        KickoffReturnDistanceModel,
        DefaultKickoffReturnDistanceModel,
        PuntDistanceContext,
        PuntReturnDistanceContext,
        FieldGoalContext,
        KickoffReturnDistanceContext,
    )
    from .misc import (
        PlayTimeElapsedModel,
        DefaultPlayTimeElapsedModel,
        PrePlayClockRunoffModel,
        DefaultPrePlayClockRunoffModel,
        CoinTossWinnerModel,
        DefaultCoinTossWinnerModel,
        KickReceiveChoiceModel,
        DefaultKickReceiveChoiceModel,
        CoinTossChoice,
        CoinTossContext,
        KickReceiveContext,
        PlayTimeElapsedContext,
        PrePlayClockRunoffContext,
    )
    from .registry import (
        ModelRegistry,
        ModelRegistryError,
        DuplicateModelError,
        ModelNotFoundError,
    )
    from .possession import (
        FumbleModel,
        DefaultFumbleModel,
        FumbleRecoveryModel,
        DefaultFumbleRecoveryModel,
        FumbleContext,
        FumbleRecoveryContext,
    )


_LAZY_IMPORTS = {
    # Base model
    "TypedModel": "pylon.models.model",
    "ModelContext": "pylon.models.model",
    "ModelExecutionError": "pylon.models.model",
    "InvalidModelReturnType": "pylon.models.model",
    # Offense
    "PlayTypeModel": "pylon.models.offense",
    "DefaultPlayTypeModel": "pylon.models.offense",
    "OffensivePlayCallModel": "pylon.models.offense",
    "DefaultOffensivePlayCallModel": "pylon.models.offense",
    "RushYardsGainedModel": "pylon.models.offense",
    "DefaultRushYardsGainedModel": "pylon.models.offense",
    "AirYardsModel": "pylon.models.offense",
    "DefaultAirYardsModel": "pylon.models.offense",
    "CompletionModel": "pylon.models.offense",
    "DefaultCompletionModel": "pylon.models.offense",
    "YardsAfterCatchModel": "pylon.models.offense",
    "DefaultYardsAfterCatchModel": "pylon.models.offense",
    "PlayTypeContext": "pylon.models.offense",
    "OffPlayCallContext": "pylon.models.offense",
    "RushYardsGainedContext": "pylon.models.offense",
    "AirYardsContext": "pylon.models.offense",
    "CompletionContext": "pylon.models.offense",
    "YardsAfterCatchContext": "pylon.models.offense",
    # Defense
    "DefensivePlayCallModel": "pylon.models.defense",
    "DefaultDefensivePlayCallModel": "pylon.models.defense",
    "DefPlayCallContext": "pylon.models.defense",
    # Personnel
    "OffensivePlayerAssignmentModel": "pylon.models.personnel",
    "DefaultOffensivePlayerAssignmentModel": "pylon.models.personnel",
    "DefensivePlayerAssignmentModel": "pylon.models.personnel",
    "DefaultDefensivePlayerAssignmentModel": "pylon.models.personnel",
    "PasserSelectionModel": "pylon.models.personnel",
    "DefaultPasserSelectionModel": "pylon.models.personnel",
    "TargettedSelectionModel": "pylon.models.personnel",
    "DefaultTargettedSelectionModel": "pylon.models.personnel",
    "RusherSelectionModel": "pylon.models.personnel",
    "DefaultRusherSelectionModel": "pylon.models.personnel",
    "KickerSelectionModel": "pylon.models.personnel",
    "DefaultKickerSelectionModel": "pylon.models.personnel",
    "PunterSelectionModel": "pylon.models.personnel",
    "DefaultPunterSelectionModel": "pylon.models.personnel",
    "PlaceKickerSelectionModel": "pylon.models.personnel",
    "DefaultPlaceKickerSelectionModel": "pylon.models.personnel",
    "PuntReturnerSelectionModel": "pylon.models.personnel",
    "DefaultPuntReturnerSelectionModel": "pylon.models.personnel",
    "KickoffReturnerSelectionModel": "pylon.models.personnel",
    "DefaultKickoffReturnerSelectionModel": "pylon.models.personnel",
    "PlayerAssignmentContext": "pylon.models.personnel",
    "PasserSelectionContext": "pylon.models.personnel",
    "TargettedSelectionContext": "pylon.models.personnel",
    "RusherSelectionContext": "pylon.models.personnel",
    "KickerSelectionContext": "pylon.models.personnel",
    "PunterSelectionContext": "pylon.models.personnel",
    "PlaceKickerSelectionContext": "pylon.models.personnel",
    "PuntReturnerSelectionContext": "pylon.models.personnel",
    "KickoffReturnerSelectionContext": "pylon.models.personnel",
    # Special teams
    "PuntDistanceModel": "pylon.models.specialteams",
    "DefaultPuntDistanceModel": "pylon.models.specialteams",
    "PuntReturnDistanceModel": "pylon.models.specialteams",
    "DefaultPuntReturnDistanceModel": "pylon.models.specialteams",
    "FieldGoalModel": "pylon.models.specialteams",
    "DefaultFieldGoalModel": "pylon.models.specialteams",
    "KickoffReturnDistanceModel": "pylon.models.specialteams",
    "DefaultKickoffReturnDistanceModel": "pylon.models.specialteams",
    "PuntDistanceContext": "pylon.models.specialteams",
    "PuntReturnDistanceContext": "pylon.models.specialteams",
    "FieldGoalContext": "pylon.models.specialteams",
    "KickoffReturnDistanceContext": "pylon.models.specialteams",
    # Misc
    "PlayTimeElapsedModel": "pylon.models.misc",
    "DefaultPlayTimeElapsedModel": "pylon.models.misc",
    "PrePlayClockRunoffModel": "pylon.models.misc",
    "DefaultPrePlayClockRunoffModel": "pylon.models.misc",
    "CoinTossWinnerModel": "pylon.models.misc",
    "DefaultCoinTossWinnerModel": "pylon.models.misc",
    "KickReceiveChoiceModel": "pylon.models.misc",
    "DefaultKickReceiveChoiceModel": "pylon.models.misc",
    "CoinTossChoice": "pylon.models.misc",
    "CoinTossContext": "pylon.models.misc",
    "KickReceiveContext": "pylon.models.misc",
    "PlayTimeElapsedContext": "pylon.models.misc",
    "PrePlayClockRunoffContext": "pylon.models.misc",
    # Possession
    "FumbleModel": "pylon.models.possession",
    "DefaultFumbleModel": "pylon.models.possession",
    "FumbleRecoveryModel": "pylon.models.possession",
    "DefaultFumbleRecoveryModel": "pylon.models.possession",
    "FumbleContext": "pylon.models.possession",
    "FumbleRecoveryContext": "pylon.models.possession",
    # Registry
    "ModelRegistry": "pylon.models.registry",
    "ModelRegistryError": "pylon.models.registry",
    "DuplicateModelError": "pylon.models.registry",
    "ModelNotFoundError": "pylon.models.registry",
}


def __getattr__(name: str):
    module_path = _LAZY_IMPORTS.get(name)
    if module_path is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = __import__(module_path, fromlist=[name])
    return getattr(module, name)


__all__ = [
    # Base model
    "TypedModel",
    "ModelContext",
    "ModelExecutionError",
    "InvalidModelReturnType",
    # Offense
    "PlayTypeModel",
    "DefaultPlayTypeModel",
    "OffensivePlayCallModel",
    "DefaultOffensivePlayCallModel",
    "RushYardsGainedModel",
    "DefaultRushYardsGainedModel",
    "AirYardsModel",
    "DefaultAirYardsModel",
    "CompletionModel",
    "DefaultCompletionModel",
    "YardsAfterCatchModel",
    "DefaultYardsAfterCatchModel",
    "PlayTypeContext",
    "OffPlayCallContext",
    "RushYardsGainedContext",
    "AirYardsContext",
    "CompletionContext",
    "YardsAfterCatchContext",
    # Defense
    "DefensivePlayCallModel",
    "DefaultDefensivePlayCallModel",
    "DefPlayCallContext",
    # Personnel
    "OffensivePlayerAssignmentModel",
    "DefaultOffensivePlayerAssignmentModel",
    "DefensivePlayerAssignmentModel",
    "DefaultDefensivePlayerAssignmentModel",
    "PasserSelectionModel",
    "DefaultPasserSelectionModel",
    "TargettedSelectionModel",
    "DefaultTargettedSelectionModel",
    "RusherSelectionModel",
    "DefaultRusherSelectionModel",
    "KickerSelectionModel",
    "DefaultKickerSelectionModel",
    "PunterSelectionModel",
    "DefaultPunterSelectionModel",
    "PlaceKickerSelectionModel",
    "DefaultPlaceKickerSelectionModel",
    "PuntReturnerSelectionModel",
    "DefaultPuntReturnerSelectionModel",
    "KickoffReturnerSelectionModel",
    "DefaultKickoffReturnerSelectionModel",
    "PlayerAssignmentContext",
    "PasserSelectionContext",
    "TargettedSelectionContext",
    "RusherSelectionContext",
    "KickerSelectionContext",
    "PunterSelectionContext",
    "PlaceKickerSelectionContext",
    "PuntReturnerSelectionContext",
    "KickoffReturnerSelectionContext",
    # Special teams
    "PuntDistanceModel",
    "DefaultPuntDistanceModel",
    "PuntReturnDistanceModel",
    "DefaultPuntReturnDistanceModel",
    "FieldGoalModel",
    "DefaultFieldGoalModel",
    "KickoffReturnDistanceModel",
    "DefaultKickoffReturnDistanceModel",
    "PuntDistanceContext",
    "PuntReturnDistanceContext",
    "FieldGoalContext",
    "KickoffReturnDistanceContext",
    # Misc
    "PlayTimeElapsedModel",
    "DefaultPlayTimeElapsedModel",
    "PrePlayClockRunoffModel",
    "DefaultPrePlayClockRunoffModel",
    "CoinTossWinnerModel",
    "DefaultCoinTossWinnerModel",
    "KickReceiveChoiceModel",
    "DefaultKickReceiveChoiceModel",
    "CoinTossChoice",
    "CoinTossContext",
    "KickReceiveContext",
    "PlayTimeElapsedContext",
    "PrePlayClockRunoffContext",
    # Possession
    "FumbleModel",
    "DefaultFumbleModel",
    "FumbleRecoveryModel",
    "DefaultFumbleRecoveryModel",
    "FumbleContext",
    "FumbleRecoveryContext",
    # Registry
    "ModelRegistry",
    "ModelRegistryError",
    "DuplicateModelError",
    "ModelNotFoundError",
]
